# Generated by Django 5.2.7 on 2025-10-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock_quantity', models.PositiveIntegerField(verbose_name='Количество на складе')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('image_urls', models.TextField(blank=True, verbose_name='Ссылки на изображения (через запятую)')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('delivery_days', models.PositiveIntegerField(verbose_name='Количество дней доставки')),
                ('sku', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Артикул')),
            ],
        ),
    ]
