# Generated by Django 5.2.7 on 2025-10-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0003_promotion_promotionbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оригинальная цена'),
        ),
    ]
