# Generated by Django 5.2.7 on 2025-10-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0009_balancetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceoperation',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Пополнение'), ('transfer', 'Перевод')], max_length=20),
        ),
        migrations.DeleteModel(
            name='BalanceTransaction',
        ),
    ]
