# Generated by Django 5.2.7 on 2025-10-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0010_alter_balanceoperation_operation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок уведомления')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('notif_type', models.CharField(choices=[('promo', 'Акции'), ('product', 'Товары'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
