# Generated by Django 5.2.7 on 2025-10-12 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstproject.promotion', verbose_name='Акция (если есть)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('promo', 'Акция'), ('product', 'Товар'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип уведомления'),
        ),
    ]
