# Generated by Django 5.2.7 on 2025-10-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0012_notification_promotion_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Язык книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='year_created',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год создания книги'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
