# Generated by Django 5.2.7 on 2025-10-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0016_alter_chat_client_alter_chat_manager_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientManagerAssignment',
        ),
    ]
