# Generated by Django 5.2.7 on 2025-10-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0021_card_delete_bankcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceoperation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
