# Generated by Django 5.2.7 on 2025-10-18 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0023_balance_card_alter_balance_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='confirmation_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(default=1, max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Введите 3 цифры CVV/CVC')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
