# Generated by Django 5.2.7 on 2025-10-18 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0024_card_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceoperation',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='firstproject.card'),
        ),
        migrations.AlterField(
            model_name='balanceoperation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='balanceoperation',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Пополнение'), ('transfer', 'Перевод'), ('add_card', 'Добавление карты'), ('delete_card', 'Удаление карты')], max_length=20),
        ),
    ]
