# Generated by Django 5.2.7 on 2025-10-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0025_balanceoperation_card_alter_balanceoperation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
    ]
