# Generated by Django 5.2.7 on 2025-10-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0026_alter_card_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_holder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, max_length=19),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
