# Generated by Django 5.2.7 on 2025-10-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0028_alter_card_card_holder_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceoperation',
            name='to_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_to', to='firstproject.card', verbose_name='Карта получателя'),
        ),
    ]
