# Generated by Django 5.2.7 on 2025-10-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0030_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_phone',
            field=models.CharField(default='+7 916 575 03 43', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('personal', '[translate:Личное уведомление]'), ('global', '[translate:Общее уведомление]')], max_length=10),
        ),
    ]
