# Generated by Django 5.2.7 on 2025-10-25 11:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0031_remove_notification_sender_notification_sender_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_point', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('pay_on_receive', 'Оплата при получении'), ('pay_online', 'Оплатить сразу')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'В пути'), ('delivered', 'Доставлен')], default='pending', max_length=20)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_code', models.CharField(blank=True, max_length=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstproject.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='firstproject.order')),
            ],
        ),
    ]
