# Generated by Django 5.2.7 on 2025-10-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0032_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('bought', 'Куплен'), ('refused', 'Отказ')], default='bought', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В пути'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
