# Generated by Django 5.2.7 on 2025-10-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0033_order_refunded_orderitem_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
