# Generated by Django 5.2.7 on 2025-10-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0034_orderitem_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В пути'), ('delivered', 'Доставлен'), ('bought', 'Куплен'), ('returned', 'Возвращен'), ('canceled', 'Отменен')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'В пути'), ('delivered', 'Доставлен'), ('bought', 'Куплен'), ('returned', 'Возвращен'), ('canceled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
