# Generated by Django 5.2.7 on 2025-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0035_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В пути'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'В пути'), ('delivered', 'Доставлен'), ('bought', 'Куплен'), ('canceled', 'Отменен'), ('refused', 'Отказ')], default='pending', max_length=20),
        ),
    ]
