# Generated by Django 5.2.7 on 2025-10-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0036_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
