# Generated by Django 5.2.7 on 2025-10-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0037_remove_orderitem_order_remove_orderitem_book_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
