# Generated by Django 5.2.7 on 2025-10-26 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0039_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pay_now', '[translate:Оплатить сразу]'), ('pay_on_delivery', '[translate:Оплатить при получении]')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', '[translate:Новый заказ]'), ('paid', '[translate:Куплен]'), ('in_transit', '[translate:В пути]'), ('delivered', '[translate:Доставлен]')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='PickUpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstproject.pickupaddress'),
        ),
    ]
