# Generated by Django 5.2.7 on 2025-11-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0042_clientstatuslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientStatusLog',
        ),
    ]
