# Generated by Django 5.2.7 on 2025-11-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0043_delete_clientstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pay_now', 'Оплатить сразу'), ('pay_on_delivery', 'Оплатить при получении')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('paid', 'Куплен'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('paid', 'Куплен'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='paid', max_length=20),
        ),
    ]
