# Generated by Django 5.2.7 on 2025-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0044_alter_order_payment_method_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pay_now', '[translate:Оплатить сразу]'), ('pay_on_delivery', '[translate:Оплатить при получении]')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', '[translate:Новый заказ]'), ('paid', '[translate:Куплен]'), ('in_transit', '[translate:В пути]'), ('delivered', '[translate:Доставлен]'), ('cancelled', '[translate:Отменён]')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('paid', '[translate:Куплен]'), ('in_transit', '[translate:В пути]'), ('delivered', '[translate:Доставлен]'), ('cancelled', '[translate:Отменён]')], default='paid', max_length=20),
        ),
    ]
