# Generated by Django 5.2.7 on 2025-11-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0045_alter_order_payment_method_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
