# Generated by Django 5.2.7 on 2025-11-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0047_alter_orderitem_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('paid', '[translate:Куплен]'), ('in_transit', '[translate:В пути]'), ('delivered', '[translate:Доставлен]'), ('cancelled', '[translate:Отменён]'), ('rejected', '[translate:Отказ]')], default='paid', max_length=20),
        ),
    ]
