# Generated by Django 5.2.7 on 2025-11-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0048_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='pickupaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PickUpAddress',
        ),
    ]
