# Generated by Django 5.2.7 on 2025-11-15 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0049_remove_orderitem_order_remove_orderitem_book_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_address', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('immediate', 'Оплатить сразу'), ('on_delivery', 'Оплатить при покупке')], max_length=20)),
                ('status', models.CharField(choices=[('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('rejected', 'Отказ'), ('bought', 'Куплен')], default='in_transit', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_days', models.PositiveIntegerField(default=0)),
                ('delivery_deadline', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstproject.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='firstproject.order')),
            ],
        ),
    ]
