# Generated by Django 5.2.7 on 2025-11-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0050_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('rejected', 'Отказ'), ('bought', 'Куплен')], default='in_transit', max_length=20),
        ),
    ]
