# Generated by Django 5.2.7 on 2025-11-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0051_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('immediate', 'Оплатить сразу'), ('on_delivery', 'Оплатить при получении')], max_length=20, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.CharField(max_length=255, verbose_name='Адрес выдачи'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstproject.book'),
        ),
    ]
