# Generated by Django 5.2.7 on 2025-11-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0052_remove_order_status_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_transit', 'В пути'), ('bought', 'Куплен'), ('rejected', 'Отказ'), ('delivered', 'Доставлен')], default='in_transit', max_length=20),
        ),
    ]
