# Generated by Django 5.2.7 on 2025-11-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0053_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
