# Generated by Django 5.2.7 on 2025-11-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0054_remove_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_deadline',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=300, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('immediate', 'Оплатить сразу'), ('on_delivery', 'Оплатить при покупке')], max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Обрабатывается'), ('cancelled', 'Отказ'), ('completed', 'Куплен')], default='processing', max_length=20),
        ),
    ]
