# Generated by Django 5.2.7 on 2025-11-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0055_remove_order_pickup_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
