# Generated by Django 5.2.7 on 2025-11-17 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0058_remove_orderitem_order_remove_orderitem_book_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итоговая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('processing', 'В процессе'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='created', max_length=20, verbose_name='Статус заказа')),
                ('client', models.ForeignKey(limit_choices_to={'profile__role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('bought', 'Куплен'), ('refused', 'Отказ')], default='in_transit', max_length=20, verbose_name='Статус товара')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstproject.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='firstproject.order')),
            ],
        ),
    ]
