# Generated by Django 5.2.7 on 2025-11-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0060_remove_orderitem_order_remove_orderitem_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ответ на вопрос 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ответ на вопрос 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_answer_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ответ на вопрос 3'),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_question_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контрольный вопрос 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_question_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контрольный вопрос 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_question_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контрольный вопрос 3'),
        ),
    ]
