# Generated by Django 5.2.7 on 2025-11-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0061_profile_security_answer_1_profile_security_answer_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='security_answer_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_answer_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_answer_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_question_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_question_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_question_3',
        ),
    ]
