# Generated by Django 5.2.7 on 2025-11-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0062_remove_profile_security_answer_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
