# Generated by Django 5.2.7 on 2025-11-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0064_profile_security_answer_1_profile_security_answer_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='security_answer_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_answer_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_answer_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_question_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_question_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_question_3',
        ),
        migrations.AddField(
            model_name='profile',
            name='security_word',
            field=models.CharField(blank=True, max_length=50, verbose_name='Резервное слово'),
        ),
    ]
