# Generated by Django 5.2.7 on 2025-11-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0065_remove_profile_security_answer_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='security_word',
        ),
    ]
