# Generated by Django 5.2.7 on 2025-11-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0066_remove_profile_security_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backup_word',
            field=models.CharField(blank=True, max_length=100, verbose_name='Резервное слово'),
        ),
    ]
