# Generated by Django 5.2.7 on 2025-11-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0068_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
