# Generated by Django 5.2.7 on 2025-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0071_remove_order_updated_at_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='admin_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ админа'),
        ),
    ]
