# Generated by Django 5.0 on 2025-12-14 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0072_bookreview_admin_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.URLField(blank=True, max_length=500, verbose_name='ВКонтакте')),
                ('telegram', models.URLField(blank=True, max_length=500, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, max_length=500, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, max_length=500, verbose_name='YouTube')),
                ('facebook', models.URLField(blank=True, max_length=500, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, max_length=500, verbose_name='Twitter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст поста')),
                ('platform', models.CharField(choices=[('vk', 'ВКонтакте'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=20, verbose_name='Платформа')),
                ('image', models.ImageField(blank=True, upload_to='social_posts/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
