# Generated by Django 5.2.2 on 2025-12-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0073_sociallink_socialpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='shares',
            field=models.IntegerField(default=0, verbose_name='Репосты'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
