# Generated by Django 5.2.2 on 2025-12-14 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0074_socialpost_shares_socialpost_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='user',
        ),
        migrations.AddField(
            model_name='socialpost',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_social_posts', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialpost',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager_social_posts', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialpost',
            name='unique_views',
            field=models.IntegerField(default=0, verbose_name='Уникальные просмотры'),
        ),
        migrations.CreateModel(
            name='SocialPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_log', to='firstproject.socialpost')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('post', 'client')},
            },
        ),
    ]
