# Generated by Django 5.2.2 on 2025-12-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0076_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='has_reply',
            field=models.BooleanField(default=False, verbose_name='Есть ответ'),
        ),
        migrations.AddField(
            model_name='review',
            name='reply_text',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ менеджера'),
        ),
    ]
