# Generated by Django 5.2.2 on 2025-12-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0078_remove_review_has_reply_review_manager_reply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐☆☆☆☆ 1'), (2, '⭐⭐☆☆☆ 2'), (3, '⭐⭐⭐☆☆ 3'), (4, '⭐⭐⭐⭐☆ 4'), (5, '⭐⭐⭐⭐⭐ 5')], default=3, verbose_name='Оценка'),
        ),
    ]
