# Generated by Django 5.0 on 2025-12-15 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0079_remove_review_sentiment_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('type', models.CharField(choices=[('contract', 'Договор'), ('invoice', 'Счет'), ('act', 'Акт выполненных работ'), ('certificate', 'Сертификат'), ('estimate', 'Смета'), ('receipt', 'Чек')], max_length=20, verbose_name='Тип документа')),
                ('client_name', models.CharField(max_length=200, verbose_name='Клиент')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('content', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/', verbose_name='Файл документа')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-date'],
            },
        ),
    ]
