# Generated by Django 5.0 on 2025-12-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0080_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='image',
        ),
        migrations.AddField(
            model_name='socialpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL картинки'),
        ),
    ]
