from django.urls import path
from .views import (
    login_view, logout_view, register_view,
    admin_page, manager_page, client_page,
    password_reset_request_view, password_reset_code_view,
    admin_users_list, admin_user_create, admin_user_edit,
    admin_user_delete, admin_user_toggle_block,
    book_catalog,
    book_create,
    book_edit,
    book_delete,
    book_detail,
    promotions_list,
    promotion_create,
    promotion_edit,
    promotion_delete,
    promotion_books_select,
    promotion_books_list,
    client_book_catalog,
    add_to_cart,
    add_to_favorites,
    client_promotion_books,
    clients_book_detail,
    cart_view, 
    favorites_view,
    client_profile_view,
    balance_view,
    clear_balance_history,
)

urlpatterns = [
    path('admin/promotions/', promotions_list, name='promotions_list'),
    path('admin/promotions/add/', promotion_create, name='promotion_create'),
    path('admin/promotions/<int:promotion_id>/edit/', promotion_edit, name='promotion_edit'),
    path('admin/promotions/<int:promotion_id>/delete/', promotion_delete, name='promotion_delete'),
    path('admin/promotions/<int:promotion_id>/books/select/', promotion_books_select, name='promotion_books_select'),
    path('admin/promotions/<int:promotion_id>/books/', promotion_books_list, name='promotion_books_list'),

    path('admin/books/', book_catalog, name='book_catalog'),
    path('admin/books/add/', book_create, name='book_create'),
    path('admin/books/<int:book_id>/edit/', book_edit, name='book_edit'),
    path('admin/books/<int:book_id>/delete/', book_delete, name='book_delete'),
    path('admin/books/<int:book_id>/', book_detail, name='book_detail'),

    path('admin/users/', admin_users_list, name='admin_users_list'),
    path('admin/users/add/', admin_user_create, name='admin_user_create'),
    path('admin/users/<int:user_id>/edit/', admin_user_edit, name='admin_user_edit'),
    path('admin/users/<int:user_id>/delete/', admin_user_delete, name='admin_user_delete'),
    path('admin/users/<int:user_id>/toggle-block/', admin_user_toggle_block, name='admin_user_toggle_block'),

    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", register_view, name="register"),
    path("admin/", admin_page, name="admin_page"),
    path("manager/", manager_page, name="manager_page"),
    path("client/", client_page, name="client_page"),
    path('catalog/', client_book_catalog, name='client_book_catalog'),
    path('catalog/book/<int:book_id>/', book_detail, name='book_detail'),
    path('catalog/add-to-cart/<int:book_id>/', add_to_cart, name='add_to_cart'),
    path('catalog/add-to-favorites/<int:book_id>/', add_to_favorites, name='add_to_favorites'),
    path('cart/', cart_view, name='cart_view'),
    path('favorites/', favorites_view, name='favorites_view'),
    path('catalog/promotion/<int:promotion_id>/', client_promotion_books, name='client_promotion_books'),
    path('catalog/book/client/<int:book_id>/', clients_book_detail, name='clients_book_detail'),
    path('profile/', client_profile_view, name='client_profile'),
    path('balance/', balance_view, name='balance'),
    path('balance/clear-history/', clear_balance_history, name='clear_balance_history'),

    path('password-reset/', password_reset_request_view, name='password_reset_request'),
    path('password-reset/code/', password_reset_code_view, name='password_reset_code'),
]
